# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e41cb1d6a381ca4e35bcebe56626bc4517553f84d6b2f45f662aa10c2a04576a1294e3e3e72eac1d189e226f7debc70c83ccce2f76d6789b38d7d429a10d29f

test:
  secret_key_base: 165c88d8e7b380e97ad7c0e7296f20fceb4580f42ea128831864bb9e92a9e108cd84a439ebedf40aa9e75e70189414f20ae50580b38920af76cf3f64343bd920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
